name: "Dialogue Checks"
description: "Check dialogues for issues"
author: 'Ashley Thew'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true

runs:
  using: 'node18'
  main: 'dist/index.js'