name: Update dialogue paths
on:
  push:
   branches: ["main"]
   paths: ["dialogue/**.json"]

jobs:
  list:
    name: Dialogue paths
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v1

      - name: Fetch action
        id: pl
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "dialogue/"
          type: ".json"

      - name: Output results
        run: |
          echo "" > dialogue/paths.txt
          for i in ${{ steps.pl.outputs.paths }}; do
          echo $i >> dialogue/paths.txt
          done
      - name: Commit files
        run: |
          git config --local user.name "AshleyThew"
          git add dialogue/paths.txt
          git commit -m "Update dialogue paths"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true